<a href="https://colab.research.google.com/github/therishabhmittal-05/MachineLearning/blob/master/MachineLearning/ML_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as  plt

In [9]:
dataset = pd.read_csv("50_Startups.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [25]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [3])] , remainder="passthrough")
X = np.array(ct.fit_transform(X))


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)

In [18]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), axis = 1))

[[116262.61 105008.31]
 [ 91489.96  96479.51]
 [ 76360.93  78239.91]
 [ 71194.69  81229.06]
 [179490.9  191050.39]
 [172318.4  182901.99]
 [ 50008.92  35673.41]
 [103038.27 101004.64]
 [ 59896.19  49490.75]
 [ 99000.9   97483.56]
 [ 98497.76  97427.84]
 [ 83942.41  81005.76]
 [119227.03 111313.02]]


In [27]:
print(regressor.predict([[1, 0, 0, 160000, 130000, 300000]]))

[180571.6]


In [28]:
print(regressor.coef_)
print(regressor.intercept_)

[-3.72e+02 -1.06e+02  4.78e+02  7.62e-01 -1.14e-03  3.35e-02]
49177.347014358194
