In [3]:
import numpy as np
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [39]:
lst = [1,2,3,4,5,6,7,8,9]
np.array(lst)
np.ones((4,4))/9
np.eye(4)/2
np.random.rand(5)
# this .rand forms gaussian distribution
np.random.randn(5)
# this .randn forms normal distribution
np.random.randint(1,20,5)

array([19,  6,  8, 10,  9])

In [60]:
arr = np.linspace(7,4,10)
print(arr)
# print(arr[2,3])

[7.         6.66666667 6.33333333 6.         5.66666667 5.33333333
 5.         4.66666667 4.33333333 4.        ]


In [97]:
lst = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(lst)
print(arr)
print(arr[0:2,0:2])
arr[0,2]
arr[1:,2:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


array([[6],
       [9]])

In [104]:
arr_2D = np.arange(25).reshape(5,5)
print(arr_2D)
arr_2D[1:4,1:4]
arr_2D[arr_2D>10].reshape(2,7)
arr_2D>10

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])