In [ ]:
import numpy as np
lst = [5,6,7,8]
vector = np.array(lst)
lst2 = [[3,4,5],[4,5,6],[2,3,4]]
matrix = np.array(lst2)
print (vector,"\n", matrix)

[5 6 7 8] 
 [[3 4 5]
 [4 5 6]
 [2 3 4]]


In [ ]:
np.arange(2,10)
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
lst = [[2,3],[4],[5,3, 4]]
np.array(lst)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [ ]:
np.arange(2, 10)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
tensor3D = np.array([[[1,2,34], [3,4,5]], [[3,4,5],[344,5,11]],[[3,4,5],[1,2,3]]])
tensor3D

array([[[  1,   2,  34],
        [  3,   4,   5]],

       [[  3,   4,   5],
        [344,   5,  11]],

       [[  3,   4,   5],
        [  1,   2,   3]]])

In [ ]:
print(tensor3D.shape)
print(tensor3D.size)
print(tensor3D.ndim)


(3, 2, 3)
18
3


In [ ]:
np.random.rand(3)

array([0.84245929, 0.30501493, 0.66139461])

In [ ]:
np.random.randn(3
                )

array([ 0.22619077, -1.86151177, -0.82286088])

In [ ]:
np.random.randint(3,100,4)

array([15, 10, 51,  8])

In [ ]:
arrRand = np.random.randint(1,100,10)
arr = np.arange(25)

In [ ]:
arr, arrRand

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]),
 array([49, 34, 72, 65, 22, 78, 91, 58, 78, 59]))

In [ ]:
arr.shape


(25,)

In [ ]:
arr.shape
arr = (arr.reshape(5,5))
arr.shape
arr.max()
arr.argmin()
arr.dtype


dtype('int64')

In [1]:
import numpy as np
arr = np.arange(11)
print(arr)
print(arr[2:6])
print(arr[4])
slice_of_arr = arr[3:7]
arr[3:7] =100
slice_of_arr = 20
print(arr)
arr_cp = arr.copy()
arr_cp[2:4] = 1
arr
arr_cp

[ 0  1  2  3  4  5  6  7  8  9 10]
[2 3 4 5]
4
[  0   1   2 100 100 100 100   7   8   9  10]


array([  0,   1,   1,   1, 100, 100, 100,   7,   8,   9,  10])